import {
  SiReact, SiNextdotjs, SiTypescript, SiJavascript, SiNodedotjs,
  SiPython, SiFirebase, SiTailwindcss, SiMysql, SiPostgresql,
  SiDocker, SiGit, SiGithub, SiLaravel, SiVuedotjs, SiAngular,
  SiPhp, SiDjango, SiMongodb, SiRedis, SiFlutter, SiAndroid,
  SiHtml5, SiCss3, SiElectron, SiCloudflare, SiNginx, SiSqlite,
  SiVercel, SiSupabase, SiExpress, SiDotnet,
} from 'react-icons/si';
import { FaServer, FaDatabase } from 'react-icons/fa';
import { TbSitemap } from 'react-icons/tb';
import type { IconType } from 'react-icons';

export const TECH_ICONS: Record<string, { icon: IconType; color: string }> = {
  'React':        { icon: SiReact,       color: '#61DAFB' },
  'Next.js':      { icon: SiNextdotjs,   color: '#e2e8f0' },
  'TypeScript':   { icon: SiTypescript,  color: '#3178C6' },
  'JavaScript':   { icon: SiJavascript,  color: '#F7DF1E' },
  'Node.js':      { icon: SiNodedotjs,   color: '#339933' },
  'Python':       { icon: SiPython,      color: '#3776AB' },
  'Firebase':     { icon: SiFirebase,    color: '#FFCA28' },
  'Tailwind CSS': { icon: SiTailwindcss, color: '#06B6D4' },
  'MySQL':        { icon: SiMysql,       color: '#4479A1' },
  'PostgreSQL':   { icon: SiPostgresql,  color: '#336791' },
  'Docker':       { icon: SiDocker,      color: '#2496ED' },
  'Git':          { icon: SiGit,         color: '#F05032' },
  'GitHub':       { icon: SiGithub,      color: '#e2e8f0' },
  'Laravel':      { icon: SiLaravel,     color: '#FF2D20' },
  'Vue.js':       { icon: SiVuedotjs,    color: '#4FC08D' },
  'Angular':      { icon: SiAngular,     color: '#DD0031' },
  'PHP':          { icon: SiPhp,         color: '#777BB4' },
  'Django':       { icon: SiDjango,      color: '#44B78B' },
  'MongoDB':      { icon: SiMongodb,     color: '#47A248' },
  'Redis':        { icon: SiRedis,       color: '#DC382D' },
  'Flutter':      { icon: SiFlutter,     color: '#02569B' },
  'Android':      { icon: SiAndroid,     color: '#3DDC84' },
  'HTML5':        { icon: SiHtml5,       color: '#E34F26' },
  'CSS3':         { icon: SiCss3,        color: '#1572B6' },
  'Electron':     { icon: SiElectron,    color: '#47848F' },
  'Cloudflare':   { icon: SiCloudflare,  color: '#F38020' },
  'Nginx':        { icon: SiNginx,       color: '#009639' },
  'SQLite':       { icon: SiSqlite,      color: '#003B57' },
  'Vercel':       { icon: SiVercel,      color: '#e2e8f0' },
  'Supabase':     { icon: SiSupabase,    color: '#3ECF8E' },
  'Express.js':   { icon: SiExpress,     color: '#e2e8f0' },
  'IIS Server':   { icon: FaServer,      color: '#0078D4' },
  '.NET MVC':     { icon: SiDotnet,      color: '#512BD4' },
  '.NET API':     { icon: SiDotnet,      color: '#512BD4' },
  'SQL Server':   { icon: FaDatabase,    color: '#CC2927' },
  'K2 Workflow':  { icon: TbSitemap,     color: '#FF6B35' },
};
